title: Junho's Blog
description: Welcome to my GitHub Pages site
baseurl: ""
url: "https://junofficial.github.io"

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Junofficial 
repo_url: 'https://github.com/junofficial/junofficial.github.io'
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist

